title: Sonny's Blog
description: This is my attempt to share my knowledge with the everyone.  Probably nothing ground breaking here.  Just some random tips.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
author: https://sonnypdx.github.io/blog