services:
  jekyll:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle/:/usr/local/bundle
    ports:
      - "4000:4000"
    #command: bash -c "jekyll serve --watch --force_polling --verbose --livereload & tail -f /dev/null"
    tty: true
    stdin_open: true
    command: sh
  